# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='classroom',
            new_name='classroom',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='field',
            field=models.CharField(choices=[('ms', 'ریاضی'), ('es', 'تجربی'), ('hs', 'انسانی')], max_length=155, verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='level',
            field=models.CharField(choices=[('7', 'هفتم'), ('8', 'هشتم'), ('9', 'نهم'), ('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], max_length=155, verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tid',
            field=models.BigIntegerField(unique=True),
        ),
    ]
