# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-17 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20190412_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(default=datetime.date(2019, 4, 17)),
        ),
    ]
