# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_auto_20190417_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(default=datetime.date(2019, 4, 25)),
        ),
    ]
