# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20190516_0912'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='student',
        #     name='profile_image',
        # ),
    ]
