# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_remove_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
