# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='/profiles/defaults.png', upload_to='profiles/'),
        ),
    ]
