# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_auto_20190523_1319'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='teacher',
        #     name='classroom',
        #     field=models.ManyToManyField(through='edu.TCC', to='edu.ClassRoom'),
        # ),
        # migrations.AlterField(
        #     model_name='teacher',
        #     name='profession',
        #     field=models.ManyToManyField(through='edu.TCC', to='edu.Course'),
        # ),
    ]
