# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('present', models.BooleanField()),
                ('present_date', models.DateField(default=django.utils.timezone.now)),
                ('register', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='edu.Register')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('present', models.BooleanField()),
                ('present_date', models.DateField(default=django.utils.timezone.now)),
                ('teacher', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='edu.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
